[package]
name = "intpolmulnonbity"
version = "0.7.0"
authors = ["serhon <serhon@protonmail.com>"]
description = "Stochastic parallelised search for counter- and extreme examples to inequalities between nonbities of 2 polynomials with nonnegative coefficients and of their product, where a nonbity of a polynomial quantifies its distinctiveness from {0,1}-one. Related to unfair 0-1-polynomials conjecture."
repository = "https://github.com/serhon/intpolmulnonbity"
keywords = ["counterexample", "Newman", "polynomial", "stochastic", "unfair"]
categories = ["science"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
num_cpus = "1.16.0"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
rayon = "1.10.0"